# Generated by Django 3.0.5 on 2022-05-24 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestorUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('color', models.CharField(choices=[(1, 'Rojo'), (2, 'Verde'), (3, 'Azul')], max_length=1)),
                ('path_image', models.ImageField(upload_to='polos')),
                ('name_modelo', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('talla', models.CharField(choices=[('S', 'Peuqeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'X-Grande')], max_length=2)),
                ('date_input', models.DateField()),
                ('marca', models.CharField(max_length=10)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsuarios.AdminProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoloFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestorUsuarios.ClientProfile')),
                ('id_polo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestorPolos.Polo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
