# Generated by Django 3.0.5 on 2022-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polo',
            name='color',
            field=models.IntegerField(choices=[(1, 'Rojo'), (2, 'Verde'), (3, 'Azul')], max_length=1),
        ),
    ]
