# Generated by Django 3.2.4 on 2022-09-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='emprendedor',
        ),
        migrations.AlterField(
            model_name='polo',
            name='colorPredonimante',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Verde', 'Verde'), ('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Morado', 'Morado'), ('Naranja', 'Naranja'), ('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Celeste', 'Celeste')], max_length=8),
        ),
    ]
