# Generated by Django 3.2.4 on 2022-09-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0001_initial'),
        ('gestorPolos', '0002_auto_20220905_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='polo',
            name='emprendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestorUsuarios.emprendedor'),
            preserve_default=False,
        ),
    ]
