# Generated by Django 3.0.5 on 2022-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0002_auto_20220524_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='date_input',
        ),
        migrations.AlterField(
            model_name='polo',
            name='color',
            field=models.IntegerField(choices=[(1, 'Rojo'), (2, 'Verde'), (3, 'Azul')]),
        ),
        migrations.AlterField(
            model_name='polo',
            name='path_image',
            field=models.ImageField(blank=True, default='E:\\U\\Semestre 9°\\Empresa\\djari-clothes-backend\\djari_clothes\\media\\polos\\default.jpg', upload_to='polos'),
        ),
    ]
