# Generated by Django 3.2.4 on 2022-09-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0003_polo_emprendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='color',
        ),
    ]
