# Generated by Django 3.0.5 on 2022-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0003_auto_20220525_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polo',
            name='path_image',
            field=models.ImageField(default='E:\\U\\Semestre 9°\\Empresa\\djari-clothes-backend\\djari_clothes\\media\\polos\\default.jpg', upload_to='polos'),
        ),
    ]
