# Generated by Django 3.2.4 on 2022-09-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0004_remove_polo_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polo',
            old_name='colorPredonimante',
            new_name='color',
        ),
    ]
