# Generated by Django 3.0.5 on 2022-05-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0005_auto_20220528_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polo',
            old_name='id_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='polofavorites',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='polofavorites',
            old_name='id_polo',
            new_name='polo',
        ),
    ]
