# Generated by Django 3.0.5 on 2022-05-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0006_auto_20220528_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='admin',
        ),
    ]
