# Generated by Django 3.0.5 on 2022-05-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0007_remove_polo_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polo',
            name='name_modelo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
