# Generated by Django 3.0.5 on 2022-05-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0008_auto_20220528_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polo',
            name='marca',
            field=models.IntegerField(choices=[(1, 'djari'), (2, 'Gucci'), (3, 'Nike'), (4, 'Adidas')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='polo',
            name='name_modelo',
            field=models.CharField(max_length=15),
        ),
    ]
