# Generated by Django 3.0.5 on 2022-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0009_auto_20220528_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polo',
            name='marca',
            field=models.IntegerField(choices=[(1, 'djari'), (2, 'Gucci'), (3, 'Nike'), (4, 'Adidas')], default=1),
        ),
    ]
