# Generated by Django 3.0.5 on 2022-05-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorPolos', '0010_auto_20220528_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polo',
            old_name='marca',
            new_name='marcas',
        ),
    ]
