# Generated by Django 3.0.5 on 2022-05-24 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestorUsuarios', '0001_initial'),
        ('gestorPolos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('count', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsuarios.ClientProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_polo', models.IntegerField(max_length=10)),
                ('price_base', models.FloatField()),
                ('id_polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorPolos.Polo')),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorVentas.Sale')),
            ],
        ),
    ]
