# Generated by Django 3.0.5 on 2022-05-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorVentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsale',
            name='count_polo',
            field=models.IntegerField(),
        ),
    ]
