# Generated by Django 3.0.5 on 2022-05-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorVentas', '0002_auto_20220524_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsale',
            old_name='price_base',
            new_name='price',
        ),
    ]
