# Generated by Django 3.0.5 on 2022-05-28 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestorVentas', '0003_auto_20220528_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsale',
            old_name='id_polo',
            new_name='polo',
        ),
        migrations.RenameField(
            model_name='detailsale',
            old_name='id_sale',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id_client',
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
