# Generated by Django 3.0.5 on 2022-05-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('numberPhone', models.CharField(max_length=9, null=True, unique=True)),
                ('is_afiliado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, null=True)),
                ('password', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=9, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsuarios.AdminProfile')),
            ],
        ),
    ]
