# Generated by Django 3.2.4 on 2022-09-06 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_emprendedor', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medio', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedioEmprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_medio', models.CharField(max_length=10)),
                ('link_medio', models.CharField(blank=True, max_length=10)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsuarios.emprendedor')),
                ('medioContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsuarios.mediocontacto')),
            ],
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='medios',
            field=models.ManyToManyField(through='gestorUsuarios.MedioEmprendedor', to='gestorUsuarios.MedioContacto'),
        ),
    ]
