# Generated by Django 3.0.5 on 2022-05-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0002_auto_20220528_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={},
        ),
        migrations.AlterModelManagers(
            name='clientprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='username',
        ),
    ]
