# Generated by Django 3.0.5 on 2022-05-28 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorVentas', '0004_auto_20220528_1600'),
        ('gestorPolos', '0005_auto_20220528_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestorUsuarios', '0003_auto_20220528_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_afiliado',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='storeaffiliate',
            name='id_admin',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeaffiliate',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
