# Generated by Django 3.2.4 on 2022-09-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0004_alter_medioemprendedor_valor_medio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medioemprendedor',
            old_name='link_medio',
            new_name='link_chat',
        ),
    ]
