# Generated by Django 3.2.4 on 2022-09-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0005_rename_link_medio_medioemprendedor_link_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='admin',
        ),
    ]
