# Generated by Django 3.2.4 on 2022-09-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0007_auto_20220911_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_permissions',
        ),
    ]
