# Generated by Django 3.2.4 on 2022-09-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0011_auto_20220911_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
