# Generated by Django 3.2.4 on 2022-09-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0012_client_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_name',
            new_name='username',
        ),
    ]
