# Generated by Django 3.2.4 on 2022-09-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0013_rename_user_name_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
