# Generated by Django 3.2.4 on 2022-09-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0014_remove_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='staff',
        ),
    ]
