# Generated by Django 3.2.4 on 2022-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsuarios', '0018_auto_20220912_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
